export const MENU_DEFAULT_APP = [
    {
        name:'Dashboard',
        path:'/',
        icon:'gauge-high'
    },
    {
        name:'Category',
        path:'/category',
        icon:'list-ul'
    },
    {
        name:'Trademark',
        path:'/trademark',
        icon:'trademark'
    },
    {
        name:'User',
        path:'/user',
        icon:'user'
    },
    {
        name:'Banner',
        path:'/banner',
        icon:'images'
    },
]